## Homework 5

## Exercise 1
### Discretization
Consider

   $$
        \dot{x(t)}=\begin{bmatrix} 
        -2 & 0 \\ 1 & 0 \end{bmatrix}x(t) + \begin{bmatrix} 
        1 \\ 0 \end{bmatrix}u(t) \\
        y(t) = \begin{bmatrix} 
        0 & 1\end{bmatrix}x(t) + 2u(t)
   $$
    
Discretize the system using a sampling time of  $T = 0.1s$. 

Assume initial conditions: $ 
       {x}(0) = \begin{bmatrix}
       0 \\ 0 \end{bmatrix}
    $and  ${u}(t) = 5$. 
    
   Find the $ 
       {x}(8)$ and ${y}(8)$ using the discrete system.

In [2]:
import numpy as np
from scipy import signal

A = np.matrix([[-2,0],[1,0]])
B = np.matrix([[1],[0]])
C = np.matrix([0, 1])
D = np.matrix([2])
T = 0.1
ut = 5

system = signal.StateSpace(A, B, C, D)
disc_sys = system.to_discrete(T)
print(disc_sys)

StateSpaceDiscrete(
array([[0.81873075, 0.        ],
       [0.09063462, 1.        ]]),
array([[0.09063462],
       [0.00468269]]),
matrix([[0, 1]]),
matrix([[2]]),
dt: 0.1
)


In [5]:
A_new = np.matrix([[0.81873075,0],[0.09063462,1]])
B_new = np.matrix([[0.09063462],[0.00468269]])

k = 80
x8 = np.zeros((2,1))
y8 = 0
for i in range(k):
    x8 = x8 + A_new**(k-i-1) @ B_new * ut
    

for j in range(k):
    y8 = y8 + C @ A_new**(k-j-1) @ B_new * ut
    
y8 = y8 + (D * ut)

hw5_dict = {"x": x8,
           "y": y8}

np.save("hw5_output.npy", hw5_dict)

__Submission:__

*   Save the solution of Exercise 1 into the dictionary as following:

```
hw5_dict
  "x": x_8
  "y": y_8
```

* The shape of x_8 must be (2,1) and that of y_8, (1,1).
* Make sure there are 2 entries in the dictionary.

*   Save into a file named "hw5_output.npy" and upload to gradescope.


*   You can submit ony twice per day. Last submission will be used for grading.
